// Pulls the vector logo out of the live homepage's SVG sprite (_scrape/raw/home.html) and writes:
//   public/brand/logo.svg        colour lock-up (Oslo Neon mark, Malmo Green wordmark), transparent
//   public/brand/logo-white.svg  the same paths in white, for dark grounds
//   public/brand/mark.svg        the mark alone (also the favicon, app/icon.svg)
//   lib/logo.ts                  the parts the preloader animates: the two mark shapes and the wordmark
import { readFileSync, writeFileSync } from "node:fs";

const html = readFileSync("_scrape/raw/home.html", "utf8");
const sym = html.match(/<symbol id="sprite-icon-logo-original" viewBox="([^"]+)">([\s\S]*?)<\/symbol>/);
if (!sym) throw new Error("logo symbol not found in the sprite");
const viewBox = sym[1];
const paths = [...sym[2].matchAll(/<path[^>]*fill="([^"]+)"[^>]*d="([^"]+)"/g)].map((m) => ({ fill: m[1], d: m[2] }));
const markD = paths.find((p) => p.fill.toUpperCase() === "#00E3A9").d;
const wordD = paths.find((p) => p.fill === "#005454").d;
// The mark path holds two subpaths: the slanted "V" stroke, then the half-circle leaf (starts at "M83.4").
const split = markD.indexOf("M83.4");
const stroke = markD.slice(0, split), leaf = markD.slice(split);

const svg = (body, vb = viewBox) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vb}">${body}</svg>\n`;
writeFileSync("public/brand/logo.svg", svg(`<path fill="#00E3A9" d="${markD}"/><path fill="#005454" d="${wordD}"/>`));
writeFileSync("public/brand/logo-white.svg", svg(`<path fill="#FFFFFF" d="${markD}"/><path fill="#FFFFFF" d="${wordD}"/>`));
// The mark spans x 0 to 83.4, y 0 to 95.4 of the lock-up.
writeFileSync("public/brand/mark.svg", svg(`<path fill="#00E3A9" d="${markD}"/>`, "-6 -6 96 108"));
writeFileSync("app/icon.svg", svg(`<rect x="-6" y="-6" width="96" height="108" rx="14" fill="#005454"/><path fill="#00E3A9" d="${markD}"/>`, "-6 -6 96 108"));

writeFileSync("lib/logo.ts", `// Generated by scripts/logo.mjs from vysusgroup.com's sprite (#sprite-icon-logo-original). Do not edit by hand.
// The lock-up is ${viewBox}: the mark (two shapes, Oslo Neon) sits at x 0 to 83.4, the wordmark (Malmo Green) from x 121.9.
export const LOGO_VIEWBOX = "${viewBox}";
export const MARK_STROKE = "${stroke}";
export const MARK_LEAF = "${leaf}";
export const WORDMARK = "${wordD}";
`);
console.log("logo ok", viewBox, paths.length, "paths");

